[package]
name = "clfrags"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "09fd631bed2af3ea89b11fdff6112a606de44d09"}
